# Generated by Django 4.1.5 on 2023-02-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pannier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pannier',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='pannier',
            name='dateCommande',
        ),
        migrations.AddField(
            model_name='commander',
            name='dateCommande',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
